# Generated by Django 5.1.6 on 2025-08-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitEntries',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('student_no', models.BigIntegerField(db_column='student_no')),
                ('student_name', models.CharField(db_column='student_name', null=True)),
                ('purpose', models.TextField(db_column='purpose', null=True)),
                ('staff', models.CharField(db_column='staff', null=True)),
                ('date', models.DateTimeField(db_column='date')),
            ],
            options={
                'db_table': 'public.visit_entries',
                'managed': False,
            },
        ),
    ]
