# Generated by Django 5.1.6 on 2025-08-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitentries',
            table='visit_entries',
        ),
    ]
